/**
 * The charting layout generated by the compiler.
 *
 * Our goal is to render multiple charts, each sharing the same x-axis, which is the time
 * and we have one or more data series rendered on each chart.
 */
export type Layout = Chart[];

/**
 * The base data for a chart.
 */
export interface Chart {
  title: string;
  domain?: [number, number];
  plots: Plot[];
}

export enum PlotKind {
  Line,
  Step,
  Bar,
  Candle,
}

export interface PlotBase<K extends PlotKind> {
  /**
   * The enum tag.
   */
  kind: K;
}

export interface LinePlot extends PlotBase<PlotKind.Line> {
  series: number;
  color: string;
}

export interface StepPlot extends PlotBase<PlotKind.Step> {
  series: number;
  color: string;
}

export interface BarPlot extends PlotBase<PlotKind.Bar> {
  series: number;
  color: string;
}

export interface CandlePlot extends PlotBase<PlotKind.Candle> {
  openSeries: number;
  highSeries: number;
  lowSeries: number;
  closeSeries: number;
  volumeSeries?: number;
}

export type Plot = LinePlot | StepPlot | BarPlot | CandlePlot;
